// Generated by CoffeeScript 1.9.2
(function() {
  var Buyer, NewItemListings, http, server;

  http = require('http');

  NewItemListings = require('./steam_services/NewItemListings.coffee');

  Buyer = require('./steam_services/Buyer.coffee');

  server = http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    return res.end('Hello World');
  });

  server.listen(9000, 'localhost');

  console.log('Server running at http://localhost:9000');

  Buyer.NewItemListings = NewItemListings;

  Buyer.login('atrainsmurf', 'aflack5234');

}).call(this);
